#!/bin/bash

# exit if not leader
ceph --admin-daemon /var/run/ceph/ceph-mon.*.asok mon_status | json_reformat | grep state | grep -qv leader && exit

# check ceph health
HEALTH=$(ceph health)
if [ "$HEALTH" != 'HEALTH_OK' ]
then
    echo Ceph is not healthy:
    ceph status
    echo
fi

# get logs for last hour
rm -f /tmp/ceph.log.lasthour
for (( i = 60; i >= 0; i-- )) ; do
    DATE=`date +'%Y-%m-%d %H:%M' -d "$i minutes ago"`
    sed -n -e "/${DATE}/p" /var/log/ceph/ceph.log >> /tmp/ceph.log.lasthour
done

# check for WRN or DBG log messages in the past hour
WARNINGS=$(grep -v INF /tmp/ceph.log.lasthour)
if [ "$WARNINGS" ]
then
    echo Warnings in ceph.log: $(grep -v INF /tmp/ceph.log.lasthour | wc -l)
    echo
fi

# check for down osd's
DOWNOSD=$(egrep 'out|down|fail|boot' /tmp/ceph.log.lasthour | grep -v pgmap)
if [ "$DOWNOSD" ]
then
    echo Out/Down/Failed OSDs:
    egrep 'out|down|fail|boot' /tmp/ceph.log.lasthour | grep -v pgmap | tail
    echo
fi

# check for slow requests
SLOW=$(grep slow /tmp/ceph.log.lasthour | grep oldest)
if [ "$SLOW" ]
then
    echo Slow Requests:
    grep slow /tmp/ceph.log.lasthour | grep oldest | tail
    echo
fi

# check for monitor elections
ELEC=$(grep election /tmp/ceph.log.lasthour)
if [ "$ELEC" ]
then
    echo Monitor Elections:
    grep election /tmp/ceph.log.lasthour | tail
    echo
fi

